const UI_TEXT={
  en:{
    interfaceLanguage:"Interface language", english:"English", chinese:"中文", languageNames:{Dutch:"Dutch"}, clearLocalData:"Clear local data", clearConfirm:"Clear all local learning data (draft, notes, ratings, progress)?", newMaterial:"New material",
    continue:"Continue", previous:"Previous", back:"Back", next:"Next", finish:"Finish", exitSession:"Exit session", play:"Play", stop:"Stop", restart:"restart",
    skip:"Skip", skipStep:"Skip this →",
    backToPreview:"Preview",
    survey:{title:"Quick feedback", progress:(n,total)=>`Question ${n} of ${total}`, mostIcon:"😊", leastIcon:"😕", most:"Which step helped most?", least:"Which step helped least?", back:"Back", submit:"Submit", skip:"Skip", close:"Close", thanks:"Thanks — that helps us shape the lessons."},
    donation:{title:"Support Lingua's development ✨", body:"A small boost helps Lingua grow for more language learners 🌱", button:"Support with €1.99", soon:"Secure checkout powered by Stripe.", feedbackLabel:"Share an idea if you want", feedbackPlaceholder:"Anything you'd like us to improve?", feedbackPrivacy:"Please don't include personal information.", feedbackSend:"Send feedback", feedbackSending:"Sending...", feedbackSent:"Thanks — feedback sent.", feedbackError:"Could not send just now."},
    scan:{eyebrow:"Quick scan", title:"Tap the words you don’t know", teacher:"Read through once and tap any word you’re unsure of — I’ll focus the vocabulary lesson on exactly those. Not sure? You can skip this.", hint:"Tap a word to mark it · tap again to unmark.", marked:(n)=>n===1?"1 word marked":`${n} words marked`, none:"No words marked yet — tap the ones you don’t know, or skip.", skip:"Skip — pick words for me", done:"Looks good →", reselect:"← Change text"},
    previewPathTitle:"What you’ll go through", previewSkipNote:"Following the path in order works best — but you can jump to any part from the sidebar, or skip whatever you like.",
    playAll:"Play page · read along", syncHint:"Each line lights up as it's read · tap any line to replay", pageOf:(a,b)=>`Page ${a} of ${b}`, previousPage:"Previous page", nextPage:"Next page",
    fullSourceAudio:"Full source audio", fullSourceRead:"Full-source read-aloud", audioUnsupported:"Audio not supported in this browser",
    audioLeft:(s)=>`${s} left`, audioTime:(a,b)=>`${a} / ${b}`,
    buildingTitle:"Building your lesson…",
    buildingSteps:["Reading your text…","Splitting it into sentences…","Translating each line…","Finding the key words…","Writing fresh examples…","Preparing your quiz…","Almost ready…"],
    buildingNote:"A real AI is translating your text and writing the lesson — this usually takes 20–40 seconds. Thanks for your patience!",
    loginTitle:"Learn any language through content you love", loginSub:"Paste a text, transcript, or article excerpt, and it becomes a complete guided learning session.",
    email:"Email", noPassword:"No password needed for this test build. Your learning stays on this device.",
    inputTitle:"Bring your material", inputSub:"Paste a short excerpt, or upload a .txt file. Best results: 1,000–3,000 characters with normal punctuation.",
    startTitle:"Choose how you'd like to learn today.", startSub:"Start with your own material, or let AI help you find something matched to your level and goals.",
    startMaterialTitle:"I already have learning material", startMaterialSub:"Turn my textbook, transcript or article into an AI lesson.", startMaterialAction:"Use my material",
    startFindTitle:"Help me find something to learn", startFindSub:"AI recommends learning materials based on my language, level and learning goals.", startFindAction:"Find material",
    findTitle:"Find something to learn", findSub:"Tell us what you are learning, and AI will recommend a few materials that fit your level and goal.",
    duration:"Full lesson time", interests:"Topics you like", topicHint:"Optional. Choose one if you have a preference.", generateMaterials:"Generate materials", generatingMaterials:"AI is writing new texts…", materialWaitHint:"This usually takes 15-30 seconds.", noSuitableMaterials:(level)=>`We couldn't find suitable ${level} materials just now. Try again, change the topic, or choose a shorter lesson time.`, chooseMaterial:"Choose one to study", useThisText:"Use this text", switchAnytime:"Pick any option below. You can switch before starting the lesson.",
    materialChoiceEasy:"Easier", materialChoiceRicher:"Richer", materialSourceTextbook:"Textbook text", materialSourceAI:"AI generated", materialSourceAIRelaxed:"AI generated · relaxed check", materialSourceSample:"Sample text",
    durationPlans:[
      {label:"10-15 min",icon:"🌱",length:"40-70 words",vocab:"~4-6 new words"},
      {label:"25-35 min",icon:"📗",length:"90-150 words",vocab:"~7-12 new words"},
    ],
    interestOptions:["Daily life","News","Culture","Travel","Work & study","Food","Technology","Society"],
    materialTipsTitle:"Need ideas?", materialTips:[
      {icon:"🎬",key:"YouTube",detail:"vlogs, explainers, street interviews",links:[
        {label:"Easy Dutch",url:"https://www.easy-languages.org/easy-dutch"},
        {label:"NOS op 3",url:"https://www.youtube.com/@nosop3"},
        {label:"Het Klokhuis",url:"https://www.youtube.com/@hetklokhuis"},
        {label:"Enzo Knol",url:"https://www.youtube.com/@EnzoKnol"},
      ]},
      {icon:"🎧",key:"Podcasts",detail:"natural speech with short excerpts",links:[
        {label:"Easy Dutch Podcast",url:"https://www.easydutch.fm/"},
        {label:"Echt Gebeurd",url:"https://echtgebeurd.net/"},
        {label:"Lang verhaal kort",url:"https://www.npo3fm.nl/podcasts/lang-verhaal-kort"},
      ]},
      {icon:"📰",key:"News",detail:"short, concrete Dutch stories",links:[
        {label:"NOS Jeugdjournaal",url:"https://jeugdjournaal.nl/"},
        {label:"NOS Nieuws",url:"https://nos.nl/"},
        {label:"NU.nl",url:"https://www.nu.nl/"},
      ]},
      {icon:"📄",key:"Your sources",detail:"material you already use",links:[
        {label:"Course notes",url:null},
        {label:"Transcript snippets",url:null},
        {label:"Emails or messages",url:null},
      ]},
    ],
    sourceHint:"Use a short excerpt you can study, not a full copyrighted work.",
    showIdeas:"Show ideas", hideIdeas:"Hide ideas",
    materialMeta:(mins,words,vocab)=>`~${mins} min full lesson · ${words} words · ~${vocab} possible new words`,
    yourText:"Your text", uploadTxt:"Upload .txt", textPlaceholder:"Paste an article, podcast transcript, newsletter excerpt, dialogue…",
    cleanNote:"Timestamps, noisy symbols, broken line breaks and spacing are lightly cleaned.", targetLanguage:"Target language *", select:"Select…",
    currentLevel:"Your current level", sessionGoal:"Session goal", overLimit:"Over the 1,200-character limit — split this into smaller chunks. Short sections usually learn better.",
    splitTitle:"This may be too much for one session", splitText:(mins)=>`This looks like a long text. For a focused lesson under 60 minutes, split it into a smaller excerpt.`,
    chooseTarget:"Choose your target language to continue.", analyzeText:"Analyze text",
    goals:["General fluency","Conversation & speaking","Reading comprehension","Vocabulary building","Exam preparation"],
    levels:["A1 — Beginner","A2 — Elementary","B1 — Intermediate","B2 — Upper-intermediate","C1 — Advanced"],
    previewTitle:"Here's your text", previewSub:"A quick read on your material before we begin.", topics:"Topics:", previewTextTitle:"Full text", previewTextHint:"Read it once before you start. Go back if you'd like a different text.",
    recommendedLevel:"Recommended level", estimatedTime:"Estimated time", vocabulary:"Vocabulary", characters:"Characters", chars:"chars",
    wordCount:(n)=>`${n} words`, diffLabels:["","Comfortable review","An easy read","Right at your level","A gentle stretch","Challenging"],
    difficultyForYou:"Difficulty for you", basedOnLevel:(a,b)=>`Based on your level (${a}) vs the text's (${b}).`,
    session:"The session", stepsInBlocks:(s,b)=>`${s} steps in ${b} blocks`, start:(m)=>`Start · ~${m} min`,
    planNames:["Learning","Grammar & Vocabulary","Practicing","Using"],
    planItems:[["Listen","Watch in your language"],["Sentence-by-sentence study"],["With subtitles","No subtitles","Recall from English"],["Write & talk with AI"]],
    heavy:(n)=>`This one has ${n} new words — quite a few. For it to really stick, try each block at least twice, and don't be shy about repeating an earlier step if it feels heavy.`,
    stepPhases:["Learning","Learning","Grammar & Vocabulary","Practicing","Practicing","Practicing","Using"],
    stepTitles:["Listen","Understand in English","Grammar & Vocabulary","Practice · with subtitles","Practice · no subtitles","Recall from English","Practice with AI"],
    stepOf:(n,total)=>`Step ${n} of ${total}`, min:(m)=>`~${m} min`,
    lockedGrammar:"Work through each sentence to unlock Continue.", lockedRecall:"Try each recall prompt before continuing.", lockedAI:"Get feedback in Part 1 and finish the Part 2 chat to unlock Finish.",
    translatingTitle:"Translating the lines", lookingUpTitle:"Looking up word meanings", aboutRemaining:(s)=>`about ${s}s left`, lineTranslating:(i,n)=>`Translating line ${i} of ${n}`, translationUnavailable:"translation unavailable",
    lookingUpWord:"Finding the short meaning and a quick detail…", studyUsage:"Study how it's used here, then try it in your own example.",
    simpleMeaning:"Simple meaning", detail:"More detail", example:"Example",
    quizLoading:"Writing a few questions about your text…", whichHeard:"Which sentence did you hear?", whichMatches:"Which sentence matches the text?",
    niceRight:"Nice — that's right.", notQuite:"Not quite — the highlighted one is it. Try replaying above.",
    selfLow:"0% · nothing yet", selfHigh:"100% · all of it",
    sr:{teacher:"Trust your ears. Play each line, then choose the sentence you heard.",purpose:"This sharpens the bridge between sound and meaning, one small decision at a time.",check:"Nailing these? Great ear. A few tricky? Replay and try once more — no rush."},
    understand:{teacher:(lang)=>`One last full listen. Play it through with ${lang} text — it should feel clear now.`,purpose:"You have met the meaning, the sound, and the useful patterns. This pass helps everything settle together.",check:"Feels clearer than the first time? That's your progress showing."},
    timed:{title:(subs)=>`Practice · ${subs?"with subtitles":"no subtitles"}`,teacherSubs:"This is shadowing. Each sentence plays on its own — read along out loud at the same time, matching the voice's rhythm.",teacherNoSubs:"Shadowing, ears only. Each sentence plays on its own — repeat it out loud right after. Reveal the text only if you get stuck.",purpose:"Speaking along with the voice gives your mouth a path to follow, so the language starts to feel usable.",how:"How this works",tips:["Each sentence plays automatically — just start speaking along with the voice.","Use Play again or slow audio to echo it a few more times.","Move on with Next whenever you're ready — Back is always there too."],ready:"Start shadowing",breath:"Each line plays by itself — read along out loud, no buttons needed.",done:(n)=>`You shadowed all ${n} sentences. Press Continue when you're ready.`,again:"Shadow again",doneCheck:"Read each one out loud? That's exactly it. Another round never hurts.",shadow:"Read along out loud",listen:"Listen first",yourTurn:"Your turn — read aloud",hide:"Hide text",reveal:"Reveal text",replay:"Play again",slow:"Slow",next:"Next",finishRound:"Finish",startSpeaking:"Start speaking",pause:"Pause",resume:"Resume",skip:"Skip",modeLabel:"Mode",modeSubs:"Read along with text",modeNoSubs:"Hidden challenge"},
    aiUse:{title:"Practice with AI",teacher:"Let's actually use it. First write a little, then have a short chat — all with today's words.",purpose:"This turns the lesson into something you can say back, gently and in context.",writeTab:"Part 2 · Write",chatTab:"Part 1 · Talk",unlock:"Finish unlocks once you've done the Part 1 chat and got feedback in Part 2.",feedback:"Get feedback",reading:"Reading…",teacherReading:"Your teacher is reading your writing…",checking:"Checking grammar, vocabulary and sentence flow — just a few seconds.",nextTalk:"Next · write",writePlaceholder:(lang)=>`Write your answer in ${lang}…`,question:(topic,lang)=>`Based on the passage — "${topic}" — what's your view? Write 3–4 sentences in ${lang} using today's words.`,saved:(n)=>`${n} words · saved locally`,feedbackTitle:(sim)=>`Feedback & suggested revision${sim?" · simulated":""}`,grammar:"Grammar",vocab:"Vocabulary",sentence:"Sentence construction",revision:"Suggested revision",mockGrammar:"Tenses look consistent. Check subject–verb agreement in your longer sentence.",mockVocab:"Nice reuse of today's words — add one connective phrase to link ideas.",mockSentence:"Clear structure. Try varying sentence length to sound more natural.",mockNote:"Showing sample feedback — the live AI check didn't respond just now, so try again in a moment for specific notes and a corrected draft."},
    focus:{title:"Today's focus",teacher:"A few things are especially worth carrying through the lesson today.",vocab:"Top vocabulary",grammar:"Top grammar",level:"Level",loading:"Choosing today's focus…"},
    recall:{title:"Recall from English",teacher:"Now make your brain reach back for the Dutch. Read the English cue, then say or type the original idea before checking.",purpose:"This forces active output, so the text becomes something you can produce, not only recognize.",englishCue:"English cue",yourDutch:"Your Dutch",placeholder:"Type the Dutch you remember…",speak:"Speak",check:"Check original",original:"Original",tryFirst:"Say or type your answer first.",done:"You tried every recall prompt.",progress:(a,b)=>`Prompt ${a} of ${b}`},
    chat:{notice:(name,lang,n)=>`You're talking with ${name}, face to face, in ${lang}. ${name} speaks first — listen, then answer out loud or type. About ${n} exchanges.`,thinking:"thinking",speaking:"speaking",yourTurn:"listening — your turn",sayAgain:"Say it again",exchange:(n,total)=>`Exchange ${n} of ${total}`,listening:"Listening — tap when done",speakAnswer:"Hold the floor · speak your answer",speakIn:(lang)=>`Speak in ${lang}. Your words appear below — edit if you like, then reply.`,typeIn:(lang)=>`Type your reply in ${lang} below (voice input works in Chrome/Edge).`,placeholder:(lang)=>`Your reply in ${lang}…`,looksGood:"Looks good",shortSentence:"Say at least a short sentence",replyTo:(name)=>`Reply to ${name}`,showTranscript:"Show transcript",feedbackTitle:(sim)=>`Conversation feedback${sim?" · simulated":""}`,fluency:"Fluency",mockDone:(lang)=>`You held a voice exchange in ${lang} using today's words — exactly the goal.`},
    done:{friend:"friend",title:(name)=>`You did it, ${name}!`,sub:(n)=>`You stayed with it through all ${n} steps. Showing up and finishing is the hard part — and you just did.`,explored:(topics)=>`Today you explored ${topics}`,more:"Bring a few more texts and we'll start to see which topics you love most — and where you spend your time.",steps:"Steps",words:"Words",sentences:"Sentences",blocks:"Blocks",comp:"Your comprehension · before vs after",rate:"One more time — how much can you understand now?",reveal:"Reveal my progress",before:"Before",after:"After",gain:(d)=>`+${d}% understanding — look at you go!`,again:"A second pass will lift this — you've got it",take:"What you're taking with you",review:"Review this lesson",new:"Bring new material"},
    refTitle:"Research basis", refText:"This flow is based on the Delft Method: understand a meaningful text first, absorb frequent words and grammar in context, then move toward conversation.", refSources:"Sources: Montens & Sciarone, Nederlands voor buitenlanders: de Delftse methode; TU Delft Centre for Languages.",
    grammarFocus:["Verb position in main clauses","Useful tense patterns","Connectors and sentence flow"],
    listen:{teacher:"Let's just listen first. Play it once and let the sound wash over you — no need to catch every word.",purpose:"Your brain starts by noticing rhythm, familiar sounds, and the shape of the language before it has to explain anything.",player:"Complete material",sub:"Full audio · no subtitles",rate:"Before we dig in — how much can you understand right now?",check:"Caught the mood or a few words? Perfect — that's all we need here. We'll check your growth at the end."},
    watch:{teacher:"Now let's make sense of it. Play along and read the meaning in a language you already know.",purpose:"Meaning comes first here, so the text feels less like a puzzle and more like a story you can follow.",check:"Does the story make sense now? If a line still feels murky, tap it again — take your time."},
    read:{teacher:(lang)=>`Let's connect sound to spelling. Read along in ${lang} while you listen.`,purpose:"Seeing the words while hearing them helps your eyes and ears agree on what is happening.",check:"Following along comfortably? Lovely. If not, replay a line or two before we move on."},
    comp:{teacher:"Quick check — no pressure at all. Pick the sentence that matches what you read.",purpose:"A small check gives you a clear signal: either you are ready to go deeper, or one more listen will help.",check:"Got them? Wonderful. Missed one? Pop back to Listen & Read — that's exactly how it's meant to work."},
    gram:{title:"Under the microscope",teacher:"Let's slow right down — one sentence at a time. We'll unpack what matters here, like a teacher sitting beside you.",purpose:"You are learning patterns from your own text, so grammar stays connected to meaning instead of floating around as rules.",sentence:(i,n)=>`Sentence ${i} of ${n}`,grammarCoach:"Grammar to notice",grammarLoading:"Reading the sentence like a teacher…",wordOrder:"Word order",slow:"Take it slow — just this one sentence for now.",noWords:"No standout new words in this sentence — enjoy the breather.",summaryTitle:"Let's pull it together",summaryTeacher:"Great work going through each sentence. Here's everything in one place to lock it in.",allVocab:"All key vocabulary",patterns:"Grammar patterns you met",examples:"Examples",translation:"Translation",showExplanation:"Show explanation",hideExplanation:"Hide explanation",review:"Review from Sentence 1",summaryCheck:"Feeling shaky on a sentence? No problem — head back to Sentence 1 and walk through again. Repetition is the whole idea.",next:"Next sentence",previous:"Previous sentence",seeSummary:"See summary",playArticle:"Play the whole text",playArticleHint:"Plays sentence by sentence — reuses the audio you already heard, so it’s free."},
    nav:{
      mods:{understanding:"Understanding",vocabulary:"Vocabulary & Grammar",shadowing:"Shadowing",recall:"Recall",using:"Using"},
      steps:{understanding:"Understanding",vocabulary:"Vocabulary & Grammar",shadowing:"Shadowing",recall:"Recall",using:"Using"},
      ctx:"Your learning path", ctxSession:(lang,level)=>`${lang} · ${level}`, backHome:"Back to home", previewHint:"Preview of your path",
    },
    diagnosis:{
      readEyebrow:"Diagnosis · Step 1", readTitle:"How much can you read?",
      readTeacher:"Tap every word you already understand — honest is best.",
      readTextLbl:(lvl)=>`The text · ${lvl}`, readWordsLbl:"Words at your level +1", gradingWords:"Grading words by level…",
      readNote:"Reading coverage updates live — unchecked words are treated as unknown and highlighted later.", coverage:"Reading coverage",
      listenEyebrow:"Diagnosis · Step 2", listenTitle:"Listen",
      listenTeacher:"Let's just listen first. Play it once and let the sound wash over you — no need to catch every word.",
      listenPurpose:"Your brain starts by noticing rhythm and the shape of the language before it has to explain anything.",
      catch:"How much did you catch?", catchHint:"One tap. The bars show roughly how much you understood.",
      tiers:[{pct:"<60%",label:"Barely",desc:"A few familiar sounds"},{pct:"~75%",label:"The gist",desc:"Main idea, missed details"},{pct:"~90%",label:"Most of it",desc:"Clear, missed a few"},{pct:"100%",label:"All of it",desc:"Effortless"}],
      diagEyebrow:"Diagnosis · Step 3", diagTitle:"Your diagnosis",
      reading:"Reading", listening:"Listening", ofWords:"of words understood", byEar:(p)=>`caught ${p} by ear`, tapFirst:"Tap a listening result on the previous step first.",
      cases:{
        golden:{emoji:"✅",kicker:"Optimal flow",name:"Perfect match — golden flow zone",body:"Your vocabulary fits the text and your ear kept up — the i+1 sweet spot.",tip:"👉 Keep this level. Go straight to shadowing & speaking."},
        acoustic:{emoji:"🎧",kicker:"Acoustic gap",name:"You read it, but your ear lagged",body:"You understand the words on the page, but the sound moved faster than your ear.",tip:"👉 Keep the text — replay the audio and drill listening before speaking."},
        overload:{emoji:"🌊",kicker:"Overload",name:"A bit much for one pass",body:"Several words were new, so meaning had to fight through the unknowns.",tip:"👉 A shorter or simpler text would land better — aim for ~70% understood."},
        comfort:{emoji:"🚀",kicker:"Comfort zone",name:"Almost too easy",body:"You breezed through reading and listening — there's little new to stretch you here.",tip:"👉 Level up next time: pick something one step harder."},
      },
    },
    celebrate:{explored:(n)=>`Today you explored ${n} new words`},
  },
  zh:{
    interfaceLanguage:"界面语言", english:"English", chinese:"中文", languageNames:{Dutch:"荷兰语"}, clearLocalData:"清除本地数据", clearConfirm:"清除所有本地学习数据（草稿、笔记、评分和进度）？", newMaterial:"新材料",
    continue:"继续", previous:"上一步", back:"返回", next:"下一步", finish:"完成", exitSession:"退出学习", play:"播放", stop:"停止", restart:"重新开始",
    skip:"跳过", skipStep:"跳过这步 →",
    backToPreview:"回到 Preview",
    survey:{title:"快速反馈", progress:(n,total)=>`第 ${n} / ${total} 题`, mostIcon:"😊", leastIcon:"😕", most:"哪个步骤帮助最大？", least:"哪个步骤帮助最小？", back:"返回", submit:"提交", skip:"跳过", close:"关闭", thanks:"谢谢 —— 这会帮我们把课程做得更好。"},
    donation:{title:"支持 Lingua 继续改进 ✨", body:"一点小小支持，会帮助 Lingua 陪更多语言学习者成长 🌱", button:"Support with €1.99", soon:"将跳转到 Stripe 安全支付页面。", feedbackLabel:"也可以顺手写点想法", feedbackPlaceholder:"有什么希望我们改进的吗？", feedbackPrivacy:"请不要填写姓名、邮箱、电话等个人信息。", feedbackSend:"发送反馈", feedbackSending:"发送中...", feedbackSent:"谢谢，反馈已发送。", feedbackError:"暂时无法发送。"},
    scan:{eyebrow:"快速扫读", title:"点出你不认识的词", teacher:"先通读一遍，把不确定的词点一下 —— 我会针对这些词来准备词汇讲解。不确定也没关系，可以跳过。", hint:"点词标记 · 再点取消。", marked:(n)=>`已标记 ${n} 个词`, none:"还没有标记 —— 点出不认识的词，或直接跳过。", skip:"跳过 — 自动帮我选词", done:"就这些 →", reselect:"← 换一篇文本"},
    previewPathTitle:"接下来会经历", previewSkipNote:"按顺序学效果最好 —— 但你可以从侧边栏跳到任意部分，也可以随时跳过。",
    playAll:"播放本页 · 跟读", syncHint:"朗读时对应句子会高亮 · 点击任意句子可重播", pageOf:(a,b)=>`第 ${a} / ${b} 页`, previousPage:"上一页", nextPage:"下一页",
    fullSourceAudio:"完整原文音频", fullSourceRead:"完整朗读", audioUnsupported:"当前浏览器不支持音频",
    audioLeft:(s)=>`剩余 ${s}`, audioTime:(a,b)=>`${a} / ${b}`,
    buildingTitle:"正在生成你的课程…",
    buildingSteps:["读取文本…","切分句子…","逐句翻译…","寻找关键词…","生成新例句…","准备小测验…","快好了…"],
    buildingNote:"AI 正在翻译文本并生成课程，通常需要 20–40 秒。谢谢耐心等待！",
    loginTitle:"用你喜欢的内容学习任何语言", loginSub:"粘贴一段文本、字幕或文章节选，它会变成一节完整的引导式学习课。",
    email:"邮箱", noPassword:"这个测试版本不需要密码。学习记录只保存在这台设备上。",
    inputTitle:"导入你的材料", inputSub:"粘贴一小段文本，或上传 .txt 文件。建议使用 1,000–3,000 字符、标点正常的内容。",
    startTitle:"今天你想怎样开始学习？", startSub:"你可以用自己的材料开始，也可以让 AI 按水平和目标帮你找内容。",
    startMaterialTitle:"我已经有学习材料", startMaterialSub:"把教材、字幕或文章变成一节 AI 课程。", startMaterialAction:"使用我的材料",
    startFindTitle:"帮我找一段内容来学", startFindSub:"AI 会根据语言、水平和学习目标推荐材料。", startFindAction:"寻找材料",
    findTitle:"寻找学习材料", findSub:"告诉我们你在学什么，AI 会推荐适合你水平和目标的材料。",
    duration:"完整课程时长", interests:"感兴趣的话题", topicHint:"可选。如果你有偏好，可以选择一个。", generateMaterials:"生成学习材料", generatingMaterials:"AI 正在生成新文本…", materialWaitHint:"通常需要 15-30 秒。", noSuitableMaterials:(level)=>`暂时没有找到适合 ${level} 的材料。请重试，换一个主题，或选择更短的学习时长。`, chooseMaterial:"选择一段来学习", useThisText:"使用这段文本", switchAnytime:"在开始课程前，你可以在下面几段材料之间切换。",
    materialChoiceEasy:"更轻松", materialChoiceRicher:"更丰富", materialSourceTextbook:"教材文本", materialSourceAI:"AI 生成", materialSourceAIRelaxed:"AI 生成 · 放宽校验", materialSourceSample:"示例文本",
    durationPlans:[
      {label:"10-15 分钟",icon:"🌱",length:"40-70 个词",vocab:"约 4-6 个生词"},
      {label:"25-35 分钟",icon:"📗",length:"90-150 个词",vocab:"约 7-12 个生词"},
    ],
    interestOptions:["日常生活","新闻","文化","旅行","工作与学习","食物","科技","社会"],
    materialTipsTitle:"找材料灵感", materialTips:[
      {icon:"🎬",key:"YouTube",detail:"vlog、解释类视频、街访",links:[
        {label:"Easy Dutch",url:"https://www.easy-languages.org/easy-dutch"},
        {label:"NOS op 3",url:"https://www.youtube.com/@nosop3"},
        {label:"Het Klokhuis",url:"https://www.youtube.com/@hetklokhuis"},
        {label:"Enzo Knol",url:"https://www.youtube.com/@EnzoKnol"},
      ]},
      {icon:"🎧",key:"Podcast",detail:"自然语速，适合截取短段落",links:[
        {label:"Easy Dutch Podcast",url:"https://www.easydutch.fm/"},
        {label:"Echt Gebeurd",url:"https://echtgebeurd.net/"},
        {label:"Lang verhaal kort",url:"https://www.npo3fm.nl/podcasts/lang-verhaal-kort"},
      ]},
      {icon:"📰",key:"新闻",detail:"短、具体、主题清楚",links:[
        {label:"NOS Jeugdjournaal",url:"https://jeugdjournaal.nl/"},
        {label:"NOS Nieuws",url:"https://nos.nl/"},
        {label:"NU.nl",url:"https://www.nu.nl/"},
      ]},
      {icon:"📄",key:"自己的材料",detail:"你已经在看的内容",links:[
        {label:"课堂笔记",url:null},
        {label:"字幕片段",url:null},
        {label:"邮件或聊天记录",url:null},
      ]},
    ],
    sourceHint:"只粘贴你可以学习使用的短节选，不要整篇搬运受版权保护的内容。",
    showIdeas:"展开灵感", hideIdeas:"收起灵感",
    materialMeta:(mins,words,vocab)=>`约 ${mins} 分钟完整课程 · ${words} 个词 · 约 ${vocab} 个可能生词`,
    yourText:"你的文本", uploadTxt:"上传 .txt", textPlaceholder:"粘贴文章、播客字幕、 newsletter 节选、对话…",
    cleanNote:"时间戳、乱码符号、断行和多余空格会被轻量清理。", targetLanguage:"目标语言 *", select:"请选择…",
    currentLevel:"当前水平", sessionGoal:"学习目标", overLimit:"超过 1,200 字符限制。建议拆成小段学习，效果会更好。",
    splitTitle:"这段可能不适合一次学完", splitText:(mins)=>`这段文本偏长。为了把单次学习控制在 60 分钟以内，建议先截取更小的一段。`,
    chooseTarget:"请选择目标语言后继续。", analyzeText:"分析文本",
    goals:["综合流利度","对话与口语","阅读理解","词汇积累","考试准备"],
    levels:["A1 — 入门","A2 — 初级","B1 — 中级","B2 — 中高级","C1 — 高级"],
    previewTitle:"这是你的文本概览", previewSub:"开始前先快速了解这份材料。", topics:"主题：", previewTextTitle:"完整文本", previewTextHint:"开始前先通读一遍。如果想换一段，可以返回。",
    recommendedLevel:"推荐水平", estimatedTime:"预计时间", vocabulary:"词汇", characters:"字符数", chars:"字符",
    wordCount:(n)=>`${n} 个词`, diffLabels:["","舒适复习","比较轻松","正适合你","温和挑战","有挑战"],
    difficultyForYou:"对你的难度", basedOnLevel:(a,b)=>`基于你的水平（${a}）和文本水平（${b}）估算。`,
    session:"学习流程", stepsInBlocks:(s,b)=>`${s} 个步骤，分成 ${b} 个模块`, start:(m)=>`开始 · 约 ${m} 分钟`,
    planNames:["学习","语法与词汇","练习","使用"],
    planItems:[["听一遍","用英文理解"],["逐句学习"],["带字幕练习","无字幕练习","英文提示回忆原文"],["和 AI 写作/对话"]],
    heavy:(n)=>`这篇材料有 ${n} 个新词，数量不少。为了真正记住，建议每个模块至少练两遍；觉得吃力时可以随时回到前面的步骤。`,
    stepPhases:["学习","学习","语法与词汇","练习","练习","练习","使用"],
    stepTitles:["听一遍","看懂意思","语法与词汇","带字幕练习","无字幕练习","英文提示回忆","和 AI 练习"],
    stepOf:(n,total)=>`第 ${n} / ${total} 步`, min:(m)=>`约 ${m} 分钟`,
    lockedGrammar:"完成逐句学习后才能继续。", lockedRecall:"请先尝试每个回忆提示再继续。", lockedAI:"完成 Part 1 反馈和 Part 2 对话后才能结束。",
    translatingTitle:"正在翻译句子", lookingUpTitle:"正在查询单词含义", aboutRemaining:(s)=>`预计还需 ${s} 秒`, lineTranslating:(i,n)=>`正在翻译第 ${i} / ${n} 句`, translationUnavailable:"暂时没有翻译",
    lookingUpWord:"正在生成简短释义和补充说明…", studyUsage:"先看它在句子里的用法，再试着自己造句。",
    simpleMeaning:"简单意思", detail:"详细说明", example:"例句",
    quizLoading:"正在根据文本生成几个问题…", whichHeard:"你听到的是哪一句？", whichMatches:"哪一句符合文本意思？",
    niceRight:"答对了，很好。", notQuite:"还差一点，高亮的是正确答案。可以重播后再试。",
    selfLow:"0% · 还不太懂", selfHigh:"100% · 全部理解",
    sr:{teacher:"相信你的耳朵。播放每一句，然后选择你听到的句子。",purpose:"这个小判断会把声音和意思连起来，一次只练一个清晰选择。",check:"做得顺的话很好；如果有几句难，重播再试一次，不急。"},
    understand:{teacher:(lang)=>`最后完整听一遍。配合 ${lang} 原文播放，现在应该清楚很多。`,purpose:"你已经见过意思、声音和常用结构了。最后这一遍会帮它们自然合在一起。",check:"比第一次清楚了吗？这就是你的进步。"},
    timed:{title:(subs)=>`练习 · ${subs?"带字幕":"无字幕"}`,teacherSubs:"这是影子跟读。每句话会自动播放——同时跟着大声读出来，尽量贴合语音的节奏。",teacherNoSubs:"影子跟读，只用耳朵。每句话会自动播放——听完立刻大声复述。卡住时再显示文本。",purpose:"跟着语音一起说，会给嘴巴一条可循的路，语言会慢慢变成你能说出口的东西。",how:"练习方式",tips:["每句话会自动播放——直接跟着语音一起开口。","可以用“再播放”或慢速多跟读几遍。","准备好了就点“下一句”；“返回”也一直可用。"],ready:"开始跟读",breath:"每句话会自动播放——跟着大声读就行，不用点按钮。",done:(n)=>`你已经跟读完 ${n} 个句子。准备好后点继续。`,again:"再跟读一遍",doneCheck:"每一句都大声读出来了吗？就是这样。多来一轮也很好。",shadow:"跟着大声读",listen:"先听",yourTurn:"轮到你 · 读出来",hide:"隐藏文本",reveal:"显示文本",replay:"再播放",slow:"慢速",next:"下一句",finishRound:"完成",startSpeaking:"开始朗读",pause:"暂停",resume:"继续",skip:"跳过",modeLabel:"模式",modeSubs:"看原文跟读",modeNoSubs:"隐藏原文挑战"},
    aiUse:{title:"和 AI 练习",teacher:"现在真正用起来。先写一点，再进行一段短对话，尽量用今天的词。",purpose:"这一步把课程变成你能回应、能表达的内容，轻一点，但要真的开口。",writeTab:"Part 2 · 写作",chatTab:"Part 1 · 对话",unlock:"完成 Part 1 对话和 Part 2 写作反馈后，就可以结束课程。",feedback:"获取反馈",reading:"阅读中…",teacherReading:"老师正在阅读你的写作…",checking:"正在检查语法、词汇和句子流畅度，几秒钟就好。",nextTalk:"下一步 · 写作",writePlaceholder:(lang)=>`用 ${lang} 写下你的回答…`,question:(topic,lang)=>`根据这段材料 “${topic}”，你怎么看？请用 ${lang} 写 3–4 句，并尽量用今天的词。`,saved:(n)=>`${n} 个词 · 已本地保存`,feedbackTitle:(sim)=>`反馈和建议修改${sim?" · 模拟":""}`,grammar:"语法",vocab:"词汇",sentence:"句子结构",revision:"建议修改",mockGrammar:"时态整体一致。较长句子里可以再检查主语和动词是否对应。",mockVocab:"今天的词用得不错，可以再加一个连接短语让意思更连贯。",mockSentence:"结构清楚。试着变化一下句子长度，会更自然。",mockNote:"正在显示示例反馈；实时 AI 刚才没有响应，稍后可再试一次获得更具体的修改。"},
    focus:{title:"今日重点",teacher:"今天有几处特别值得一路带着学。",vocab:"重点词汇",grammar:"重点语法",level:"等级",loading:"正在提炼今日重点…"},
    recall:{title:"英文提示回忆",teacher:"现在让大脑主动把荷兰语找回来。先看英文提示，然后说出或写出原文意思，再查看答案。",purpose:"这一步会强迫主动输出，让文本不只是能看懂，也能说出来。",englishCue:"英文提示",yourDutch:"你的荷兰语",placeholder:"写下你记得的荷兰语…",speak:"语音输入",check:"查看原文",original:"原文",tryFirst:"请先说出或写下你的答案。",done:"每个回忆提示都尝试过了。",progress:(a,b)=>`第 ${a} / ${b} 题`},
    chat:{notice:(name,lang,n)=>`你正在和 ${name} 面对面用 ${lang} 对话。${name} 会先说，听完后你可以开口回答，也可以打字。大约 ${n} 轮。`,thinking:"思考中",speaking:"正在说话",yourTurn:"正在听你说",sayAgain:"再说一遍",exchange:(n,total)=>`第 ${n} / ${total} 轮`,listening:"正在听 · 说完后点击",speakAnswer:"轮到你 · 说出回答",speakIn:(lang)=>`请用 ${lang} 说。你的话会出现在下面，可以修改后再发送。`,typeIn:(lang)=>`请在下面用 ${lang} 打字回复（Chrome/Edge 支持语音输入）。`,placeholder:(lang)=>`用 ${lang} 回复…`,looksGood:"看起来不错",shortSentence:"至少说一个短句",replyTo:(name)=>`回复 ${name}`,showTranscript:"显示对话记录",feedbackTitle:(sim)=>`对话反馈${sim?" · 模拟":""}`,fluency:"流利度",mockDone:(lang)=>`你已经用 ${lang} 完成了一段语音交流，并且用到了今天的词，这正是目标。`},
    done:{friend:"同学",title:(name)=>`${name}，你完成了！`,sub:(n)=>`你完整走完了 ${n} 个学习步骤。真正难的是开始并坚持到最后，而你已经做到了。`,explored:(topics)=>`今天你学习了 ${topics}`,more:"多带几段文本来，我们会慢慢看出你喜欢哪些主题、常在哪些地方投入时间。",steps:"步骤",words:"词汇",sentences:"句子",blocks:"模块",comp:"理解度 · 前后对比",rate:"最后再问一次：现在你大概能理解多少？",reveal:"查看我的进步",before:"之前",after:"之后",gain:(d)=>`理解度 +${d}% ，很漂亮`,again:"再来一遍会继续提升，你已经在路上了",take:"你带走的内容",review:"复习这节课",new:"导入新材料"},
    refTitle:"研究依据", refText:"这套流程基于 Delft Method：先理解一段有意义的文本，再在上下文里吸收高频词和语法，最后过渡到真实表达。", refSources:"来源：Montens & Sciarone《Nederlands voor buitenlanders: de Delftse methode》；TU Delft Centre for Languages。",
    grammarFocus:["主句里的动词位置","文本里的常见时态","连接词和句子衔接"],
    listen:{teacher:"先只听一遍。播放后让声音自然进入耳朵，不需要每个词都听懂。",purpose:"大脑会先捕捉节奏、熟悉的声音和语言轮廓，不必马上解释每个细节。",player:"完整材料",sub:"完整音频 · 无字幕",rate:"正式学习前，你现在大概能理解多少？",check:"听出了大意或几个词就很好。最后我们会再对比一次你的进步。"},
    watch:{teacher:"现在先把意思看懂。边播放边读你已经熟悉的语言里的含义。",purpose:"先有意思，文本就不再像谜题，而更像一段你能跟上的故事。",check:"现在故事更清楚了吗？如果某一句还模糊，点它再听一次，慢慢来。"},
    read:{teacher:(lang)=>`把声音和拼写连起来。听的时候一起阅读 ${lang} 原文。`,purpose:"同时听到和看到单词，会更容易记住。",check:"能跟上了吗？如果还不稳，先重播一两句再继续。"},
    comp:{teacher:"快速检查一下，没有压力。选择和文本意思相符的句子。",purpose:"一个小检查会给你清楚的信号：可以继续深入，或者先多听一遍。",check:"完成了吗？很好。错了一题也没关系，回到“听读结合”再过一遍就对了。"},
    gram:{title:"逐句拆解",teacher:"我们放慢速度，一次只看一句。只拆这句里真正值得注意的地方，像老师坐在旁边。",purpose:"你会从自己的文本里学结构，所以语法不会漂在空中，而是一直连着意思。",sentence:(i,n)=>`第 ${i} / ${n} 句`,grammarCoach:"这句的语法重点",grammarLoading:"正在像老师一样读这句话…",wordOrder:"语序",slow:"慢慢来，现在只专注这一句。",noWords:"这一句没有特别突出的新词，轻松一下。",summaryTitle:"整理一下",summaryTeacher:"逐句学完了，很棒。这里把重点放在一起，帮助你巩固。",allVocab:"全部重点词汇",patterns:"遇到的语法模式",examples:"例句",translation:"翻译",showExplanation:"展开解释",hideExplanation:"收起解释",review:"从第 1 句复习",summaryCheck:"如果某一句还不稳，回到第 1 句再走一遍。重复本来就是学习的一部分。",next:"下一句",previous:"上一句",seeSummary:"查看总结",playArticle:"播放整篇",playArticleHint:"逐句播放 —— 复用你刚听过的音频，不额外耗费。"},
    nav:{
      mods:{understanding:"理解",vocabulary:"词汇与语法",shadowing:"跟读",recall:"回忆",using:"输出"},
      steps:{understanding:"理解",vocabulary:"词汇与语法",shadowing:"跟读",recall:"回忆",using:"输出"},
      ctx:"你的学习路径", ctxSession:(lang,level)=>`${lang} · ${level}`, backHome:"返回首页", previewHint:"路径预览",
    },
    diagnosis:{
      readEyebrow:"诊断 · 第 1 步", readTitle:"你能读懂多少？",
      readTeacher:"把你已经认识的词都点一下——诚实最好。",
      readTextLbl:(lvl)=>`文本 · ${lvl}`, readWordsLbl:"你水平 +1 的词", gradingWords:"正在按等级给词打分…",
      readNote:"阅读理解度会实时更新——没点的词会被当作生词，之后重点高亮。", coverage:"阅读理解度",
      listenEyebrow:"诊断 · 第 2 步", listenTitle:"听一遍",
      listenTeacher:"先只听一遍。播放一次，让声音自然进入耳朵，不用每个词都听懂。",
      listenPurpose:"大脑会先捕捉节奏和语言的轮廓，然后才需要解释含义。",
      catch:"你听懂了多少？", catchHint:"点一下就好。信号条大致表示你听懂的比例。",
      tiers:[{pct:"<60%",label:"几乎听不懂",desc:"只有几个熟悉的音"},{pct:"~75%",label:"抓住大意",desc:"懂主旨，漏了细节"},{pct:"~90%",label:"大部分",desc:"清楚，漏了几个"},{pct:"100%",label:"全部",desc:"毫不费力"}],
      diagEyebrow:"诊断 · 第 3 步", diagTitle:"你的诊断",
      reading:"阅读", listening:"听力", ofWords:"的词能读懂", byEar:(p)=>`听力约 ${p}`, tapFirst:"请先在上一步点选一个听力结果。",
      cases:{
        golden:{emoji:"✅",kicker:"最佳区间",name:"完美匹配——黄金流畅区",body:"你的词汇量与文本相符，耳朵也跟得上——正是 i+1 的甜蜜点。",tip:"👉 保持这个难度，直接进入跟读与口语。"},
        acoustic:{emoji:"🎧",kicker:"听力缺口",name:"能读懂，但耳朵慢半拍",body:"纸面上的词你都懂，但声音比你的耳朵快。",tip:"👉 保留文本——先重播音频、加练听力再开口。"},
        overload:{emoji:"🌊",kicker:"信息过载",name:"一次有点太多了",body:"生词偏多，意思得从未知里挤出来。",tip:"👉 换更短或更简单的文本会更合适——目标约 70% 理解。"},
        comfort:{emoji:"🚀",kicker:"舒适区",name:"有点太简单了",body:"阅读和听力都很轻松——这里没什么能拉伸你的新东西。",tip:"👉 下次升级：选难一档的内容。"},
      },
    },
    celebrate:{explored:(n)=>`今天你学了 ${n} 个新词`},
  }
};

function langName(t,lang){ return (t.languageNames&&t.languageNames[lang])||lang; }

export { UI_TEXT, langName };
